# Generated by Django 5.0.2 on 2024-02-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantedCropsModel',
            fields=[
                ('pcr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pcr_label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colheita_plantada',
            },
        ),
        migrations.CreateModel(
            name='AgricultureModel',
            fields=[
                ('agr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agr_productor_name', models.CharField(max_length=500)),
                ('agr_farm_name', models.CharField(max_length=500)),
                ('agr_cnpf', models.CharField(max_length=20, null=True)),
                ('agr_cnpj', models.CharField(max_length=20, null=True)),
                ('agr_total_area_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agr_arable_are_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agr_vegetable_area_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agr_id_city_id', to='region.citymodel')),
            ],
            options={
                'db_table': 'agricultura',
            },
        ),
        migrations.CreateModel(
            name='PlantedCropsAgriModel',
            fields=[
                ('pca_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agri_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pca_id_agri_id', to='agriculture.agriculturemodel')),
                ('pcr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pca_id_pcr_id', to='agriculture.plantedcropsmodel')),
            ],
            options={
                'db_table': 'agricultura_colheita_plantada',
            },
        ),
    ]
