# Generated by Django 5.0.2 on 2024-02-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturemodel',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='agr_id_city_id', to='region.citymodel'),
        ),
    ]
