# Generated by Django 5.0.2 on 2024-02-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('pai_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pai_nome', models.CharField(max_length=60)),
                ('pai_nome_pt', models.CharField(max_length=60)),
                ('pai_sigla', models.CharField(max_length=2, null=True)),
                ('pai_bacen', models.IntegerField()),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('std_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_nome', models.CharField(max_length=60)),
                ('std_uf', models.CharField(max_length=2)),
                ('std_ibge', models.IntegerField()),
                ('std_ddd', models.CharField(max_length=500, null=True)),
                ('pai_id', models.ForeignKey(db_column='pai_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='region.countrymodel')),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_nome', models.CharField(max_length=120)),
                ('city_ibge', models.IntegerField(null=True)),
                ('city_lat_lon', models.CharField(max_length=500, null=True)),
                ('city_latitude', models.FloatField(null=True)),
                ('city_longitude', models.FloatField(null=True)),
                ('city_cod_tom', models.SmallIntegerField(default=0, null=True)),
                ('std_id', models.ForeignKey(db_column='std_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='region.statemodel')),
            ],
            options={
                'db_table': 'cidade',
            },
        ),
    ]
