# Generated by Django 5.0.2 on 2024-02-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='usr_password',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
