# Generated by Django 5.0.2 on 2024-02-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_usr_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='usr_password',
        ),
    ]
